# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on: ["push", "pull_request"]


jobs:

  build:
    name: Build
    runs-on: windows-latest
    steps:

    - uses: actions/checkout@v1

    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: npm install
      run: npm install
      
    - name: npm test
      run: npm test

    - name: Coveralls
      uses: coverallsapp/github-action@v2
            
